// <auto-generated />
using System;
using InsuranceAgency.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InsuranceAgency.Data.Migrations
{
    [DbContext(typeof(InsuranceDbContext))]
    partial class InsuranceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InsuranceAgency.Domain.Entities.Claim", b =>
                {
                    b.Property<int>("ClaimID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClaimID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(15,2)");

                    b.Property<DateTime>("ClaimDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PolicyID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ClaimID");

                    b.HasIndex("PolicyID");

                    b.ToTable("Claims");
                });

            modelBuilder.Entity("InsuranceAgency.Domain.Entities.Client", b =>
                {
                    b.Property<int>("ClientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ClientID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("InsuranceAgency.Domain.Entities.FuneralPolicy", b =>
                {
                    b.Property<int>("FuneralPolicyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FuneralPolicyID"));

                    b.Property<decimal>("CoverageAmount")
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("FuneralType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PolicyID")
                        .HasColumnType("int");

                    b.HasKey("FuneralPolicyID");

                    b.HasIndex("PolicyID")
                        .IsUnique();

                    b.ToTable("FuneralPolicies");
                });

            modelBuilder.Entity("InsuranceAgency.Domain.Entities.LegalPolicy", b =>
                {
                    b.Property<int>("LegalPolicyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LegalPolicyID"));

                    b.Property<string>("LegalType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("MaxCoverageAmount")
                        .HasColumnType("decimal(15,2)");

                    b.Property<int>("PolicyID")
                        .HasColumnType("int");

                    b.HasKey("LegalPolicyID");

                    b.HasIndex("PolicyID")
                        .IsUnique();

                    b.ToTable("LegalPolicies");
                });

            modelBuilder.Entity("InsuranceAgency.Domain.Entities.LifePolicy", b =>
                {
                    b.Property<int>("LifePolicyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LifePolicyID"));

                    b.Property<string>("Beneficiary")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("CoverageAmount")
                        .HasColumnType("decimal(15,2)");

                    b.Property<int>("PolicyID")
                        .HasColumnType("int");

                    b.HasKey("LifePolicyID");

                    b.HasIndex("PolicyID")
                        .IsUnique();

                    b.ToTable("LifePolicies");
                });

            modelBuilder.Entity("InsuranceAgency.Domain.Entities.Policy", b =>
                {
                    b.Property<int>("PolicyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PolicyID"));

                    b.Property<int>("ClientID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PolicyType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("PremiumAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PolicyID");

                    b.HasIndex("ClientID");

                    b.HasIndex("PolicyNumber")
                        .IsUnique();

                    b.ToTable("Policies");
                });

            modelBuilder.Entity("InsuranceAgency.Domain.Entities.Claim", b =>
                {
                    b.HasOne("InsuranceAgency.Domain.Entities.Policy", "Policy")
                        .WithMany("Claims")
                        .HasForeignKey("PolicyID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("InsuranceAgency.Domain.Entities.FuneralPolicy", b =>
                {
                    b.HasOne("InsuranceAgency.Domain.Entities.Policy", "Policy")
                        .WithOne("FuneralPolicy")
                        .HasForeignKey("InsuranceAgency.Domain.Entities.FuneralPolicy", "PolicyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("InsuranceAgency.Domain.Entities.LegalPolicy", b =>
                {
                    b.HasOne("InsuranceAgency.Domain.Entities.Policy", "Policy")
                        .WithOne("LegalPolicy")
                        .HasForeignKey("InsuranceAgency.Domain.Entities.LegalPolicy", "PolicyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("InsuranceAgency.Domain.Entities.LifePolicy", b =>
                {
                    b.HasOne("InsuranceAgency.Domain.Entities.Policy", "Policy")
                        .WithOne("LifePolicy")
                        .HasForeignKey("InsuranceAgency.Domain.Entities.LifePolicy", "PolicyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("InsuranceAgency.Domain.Entities.Policy", b =>
                {
                    b.HasOne("InsuranceAgency.Domain.Entities.Client", "Client")
                        .WithMany("Policies")
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("InsuranceAgency.Domain.Entities.Client", b =>
                {
                    b.Navigation("Policies");
                });

            modelBuilder.Entity("InsuranceAgency.Domain.Entities.Policy", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("FuneralPolicy");

                    b.Navigation("LegalPolicy");

                    b.Navigation("LifePolicy");
                });
#pragma warning restore 612, 618
        }
    }
}
